### ISSUE TITLE
Color is not working for light sources

### ISSUE THREAD

**Issue by Avitale34** [Malekal4699/LightsHUD#20]
It seems like the radius and effects work fine but the color seems to always be white.

**Comment by Malekal4699** [comment]
I'll have a look

**Comment by Malekal4699** [comment]
Hi, it works, but only if you select custom light in the setup. 
I've got to rework the system settings and how they impact tokens, because currently it's like a single setup for everyone. 
These should be a default setting and then remember changes made by the GM for each tokens.

Stay put, that's actually coming after I fix the linked token issues.

Closing the issue.
