### ISSUE TITLE
Feature request - Custom Light spell name

### ISSUE THREAD

**Issue by lucaspicerni** [Malekal4699/LightsHUD#37]
Hi! It would be great to be able to configure a custom name for the spell that the module checks on the token, instead of always looking for Light.

**Comment by Malekal4699** [comment]
Hi, update to the latest release, a new box has been added for that. Thanks,From: lucaspicerniSent: Monday, April 4, 2022 2:09 PMTo: Malekal4699/LightsHUDCc: SubscribedSubject: [Malekal4699/LightsHUD] Feature request - Custom Light spell name (Issue #37) Hi! It would be great to be able to configure a custom name for the spell that the module checks on the token, instead of always looking for Light.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Malekal4699** [comment]
Hi,

have you updated to the latest release? (Released this morning.)

<img width="456" alt="image" src="https://user-images.githubusercontent.com/78604153/161612788-73772ae8-a3f9-48cf-805f-74ba032ee7b5.png">

**Comment by lucaspicerni** [comment]
Oh, I'm sorry, I hadn't seen it! But what a good coincidence, thanks for the work!
